repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (system)
        entry: ruff
        language: system
        types: [python]
        pass_filenames: false
        args: ["check", "--fix"]

      - id: mypy
        name: mypy (system)
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ["-p", "splurge_unittest_to_pytest"]

      - id: pytest-suite
        name: pytest test suite (system)
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        # Override pyproject's addopts during pre-commit so coverage/xdist options
        # (which may require plugins not present in the pre-commit environment)
        # are not applied. Run tests serially and without pytest-cov plugin.
        args: ["-q", "-o", "addopts=", "-p", "no:pytest_cov", "tests"]

