import warnings



def pytest_configure(config):
    # Suppress SyntaxWarning generated by test data that intentionally uses
    # bad Python such as `assert 1 is not None`. We keep these data files as
    # examples for the converter; users should fix such code in their codebase.
    warnings.filterwarnings(
        "ignore",
        message=r"\"is not\" with 'int' literal",
        category=SyntaxWarning,
    )

    # Also ignore generic SyntaxWarning arising during conversion tests where
    # converted temporary files may contain `assert X is not None` with
    # literal values (these are test fixtures, not real code).
    warnings.filterwarnings(
        "ignore",
        category=SyntaxWarning,
    )
