name: Quick Code Quality Checks

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  quick-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        allow-prereleases: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy

    - name: Run Ruff Check
      run: |
        echo "Running Ruff check with Python 3.12"
        ruff check

    - name: Run MyPy Type Check
      run: |
        echo "Running MyPy type check with Python 3.12"
        mypy splurge_unittest_to_pytest
