name: Full Test Suite

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
    # Skip PRs created by GitHub Actions to avoid infinite loops
    paths-ignore:
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run tests without coverage
      run: |
        echo "Running full test suite with Python ${{ matrix.python-version }}"
        python -m pytest tests/ -v --no-cov --tb=short

    - name: Generate coverage report (Python 3.12 only)
      if: matrix.python-version == '3.12'
      run: |
        echo "Generating coverage report with Python 3.12"
        python -m pytest tests/ --cov=splurge_unittest_to_pytest --cov-report=xml --cov-report=html

    - name: Upload coverage artifacts
      if: matrix.python-version == '3.12'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports-python-${{ matrix.python-version }}
        path: |
          ./coverage.xml
          ./htmlcov/
        retention-days: 30
