name: PR — debug tests

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  debug-tests:
    name: Run tests with SPLURGE_TRANSFORM_DEBUG
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Prefer installing from pyproject.toml using editable install and the 'dev' extras.
          pip install -e .[dev] || pip install "-r" requirements.txt || true

      - name: Run tests (debug mode)
        env:
          SPLURGE_TRANSFORM_DEBUG: '1'
        run: |
          pytest -q
